from app.serializers.ClienteSerializer import ClienteSerializer
from app.serializers.ItemSerializer import ItemSerializer
from app.serializers.PedidoSerializer import PedidoSerializer
from app.serializers.ProdutoSerializer import ProdutoSerializer
from app.serializers.RentabilidadeSerializer import RentabilidadeSerializer

